name: Deploy to Cloud Foundry
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  pull-requests: read
jobs:
  deploy:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x  
          
      - name: Login to Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli
          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
      - name: Clone and prepare projects & Build and deploy
        run: |
          echo "Working directory"
          pwd
          ls
          echo "list of files"
          git clone --single-branch --branch develop https://github.com/cap-js/sdm.git
          git clone --single-branch --branch sdmIncidents https://github.com/cap-js/incidents-app.git
          echo "list of files after clone"
          pwd
          ls
          cd sdm
          pwd
          echo "pwd"
          npm pack
          mv cap-js-sdm-1.0.0.tgz ../incidents-app
          cd ../incidents-app
          echo "incidents-app"
          pwd
          npm i cap-js-sdm-1.0.0.tgz
          
      
